name: Emotion Pictures
favicon: null
layout_spectrum: 0.78168
typography_spectrum: 0.8207885
title: Emotion Pictures
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFF5D9'
    - '#000002'
    - '#553E15'
    - '#BD9767'
    - '#029B4A'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
