favicon: null
name: 1stphoto Site
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2258064
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.3548387
typography_spectrum: 0.1362007
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4301075
analytics:
  twitter: null
  google: null
  facebook: null
