name: 1stphoto Site
favicon: null
layout_spectrum: 0.3549477627966553
typography_spectrum: 0.8997220178134739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#282633'
    - '#111728'
    - '#ffffff'
    - '#443434'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
