name: Emotion Pictures
favicon: null
layout_spectrum: 0.84978
typography_spectrum: 0
title: Emotion Pictures
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#d3d3d3'
    - '#2a2a2a'
    - '#575757'
  brandStrength: 0
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.5394265
purpose: []
