title: Emotion Pictures
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.875
  brandStrength: 0.625
  rhythmicContrast: 0.5394265
  brandColors:
    - '#f8fefa'
    - '#000000'
    - '#959595'
    - '#ced0df'
    - '#7d5140'
  lightness: 0.3888889
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Emotion Pictures
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8207885
layout_spectrum: 0.7562724
