name: 1stphoto Site
favicon: null
layout_spectrum: 0.3549477627966553
typography_spectrum: 0.8997220178134739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6686055746395141
  lightness: 0.47560247662477195
  saturation: 0.8470827091950923
  rhythmicContrast: 0.7599512476008385
purpose: []
