name: Emotion Pictures
favicon: null
layout_spectrum: 0.54691
typography_spectrum: 0.8207885
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Emotion Pictures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8fefa'
    - '#000000'
    - '#959595'
    - '#ced0df'
    - '#7d5140'
  brandStrength: 0.625
  lightness: 0.3888889
  saturation: 0.875
  rhythmicContrast: 0.5394265
purpose: []
