title: Emotion Pictures
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8243728
  brandStrength: 0.7204301
  lightness: 0.3888889
  brandColors:
    - '#FFF5D9'
    - '#000002'
    - '#553E15'
    - '#BD9767'
    - '#029B4A'
  rhythmicContrast: 0.6953405
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Emotion Pictures
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8207885
layout_spectrum: 0.8835126
